### ISSUE TITLE
Number of partials limit

### ISSUE THREAD

**Issue by nvmker** [stablum/AdditiveVoice#15]
Hi,
First bug report here :)
Looks like increasing number of partials make Daisy unresponsive, so I think limiting this parameter would be great.
Thanks!
Update:
I see that the partials limited to 100, I think there is makes sense to limit it to lower value, in my case Daisy hanging when partials number is set to about 38-40.

**Comment by stablum** [comment]
Hi @nvmker , thank you for posting this! :) 
I need to think about this because while on one side it's good to have a product that seems to be always working smoothly, on the other side I would not hinder a user to push the tool to its limits.
Currently, as a compromise solution I'm displaying an exclamation point when the settings might lead the product to glitches or crashes.
But I will think about this and eventually implement the solution you suggested. Thank you! :)

**Comment by stablum** [comment]
Hi @nvmker ,

I just implemented your suggestion in v0.76 ! :)
I capped the maximum value of the partials as 40 for Sine and the Poly\* waveforms, 80 for all other waveforms. 

Firmware: https://github.com/stablum/AdditiveVoice/blob/master/build/additive_voice_0.76.bin

Enjoy! :)

**Comment by nvmker** [comment]
Thanks!
